//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB.TelegramBot.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AB.TelegramBot.Resources.Strings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I do not work with this thing yet :(.
        /// </summary>
        public static string IDonotWortkWithThis {
            get {
                return ResourceManager.GetString("IDonotWortkWithThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand the message. Please, try again..
        /// </summary>
        public static string IDontUnderstand {
            get {
                return ResourceManager.GetString("IDontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I do not work with documents yet :(.
        /// </summary>
        public static string IDontWorkWithDocuments {
            get {
                return ResourceManager.GetString("IDontWorkWithDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I do not work with photo yet :(.
        /// </summary>
        public static string IDontWorkWithPhoto {
            get {
                return ResourceManager.GetString("IDontWorkWithPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I have no idea what do you want....
        /// </summary>
        public static string IHaveNoIdeaWhatDoYouWant {
            get {
                return ResourceManager.GetString("IHaveNoIdeaWhatDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input currency is not correct.
        /// </summary>
        public static string InputCurrencyIsNotCorrect {
            get {
                return ResourceManager.GetString("InputCurrencyIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data is not correct.
        /// </summary>
        public static string InputDataIsNotCorrect {
            get {
                return ResourceManager.GetString("InputDataIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input date is not correct.
        /// </summary>
        public static string InputDateIsNotCorrect {
            get {
                return ResourceManager.GetString("InputDateIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not available.
        /// </summary>
        public static string IsNotAvailable {
            get {
                return ResourceManager.GetString("IsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not correct.
        /// </summary>
        public static string IsNotCorrect {
            get {
                return ResourceManager.GetString("IsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, try later....
        /// </summary>
        public static string SomethingWentWrongTryLater {
            get {
                return ResourceManager.GetString("SomethingWentWrongTryLater", resourceCulture);
            }
        }
    }
}
